/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgulhoMaranhenseRouteImport } from './routes/orgulho-maranhense'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as FidelidadeRouteImport } from './routes/fidelidade'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as IndexRouteImport } from './routes/index'

const OrgulhoMaranhenseRoute = OrgulhoMaranhenseRouteImport.update({
  id: '/orgulho-maranhense',
  path: '/orgulho-maranhense',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const FidelidadeRoute = FidelidadeRouteImport.update({
  id: '/fidelidade',
  path: '/fidelidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/carrinho': typeof CarrinhoRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/fidelidade': typeof FidelidadeRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/orgulho-maranhense': typeof OrgulhoMaranhenseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/carrinho': typeof CarrinhoRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/fidelidade': typeof FidelidadeRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/orgulho-maranhense': typeof OrgulhoMaranhenseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/carrinho': typeof CarrinhoRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/fidelidade': typeof FidelidadeRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/orgulho-maranhense': typeof OrgulhoMaranhenseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cardapio'
    | '/carrinho'
    | '/conta'
    | '/contato'
    | '/fidelidade'
    | '/historia'
    | '/login'
    | '/orgulho-maranhense'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardapio'
    | '/carrinho'
    | '/conta'
    | '/contato'
    | '/fidelidade'
    | '/historia'
    | '/login'
    | '/orgulho-maranhense'
  id:
    | '__root__'
    | '/'
    | '/cardapio'
    | '/carrinho'
    | '/conta'
    | '/contato'
    | '/fidelidade'
    | '/historia'
    | '/login'
    | '/orgulho-maranhense'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardapioRoute: typeof CardapioRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ContaRoute: typeof ContaRoute
  ContatoRoute: typeof ContatoRoute
  FidelidadeRoute: typeof FidelidadeRoute
  HistoriaRoute: typeof HistoriaRoute
  LoginRoute: typeof LoginRoute
  OrgulhoMaranhenseRoute: typeof OrgulhoMaranhenseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orgulho-maranhense': {
      id: '/orgulho-maranhense'
      path: '/orgulho-maranhense'
      fullPath: '/orgulho-maranhense'
      preLoaderRoute: typeof OrgulhoMaranhenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fidelidade': {
      id: '/fidelidade'
      path: '/fidelidade'
      fullPath: '/fidelidade'
      preLoaderRoute: typeof FidelidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardapioRoute: CardapioRoute,
  CarrinhoRoute: CarrinhoRoute,
  ContaRoute: ContaRoute,
  ContatoRoute: ContatoRoute,
  FidelidadeRoute: FidelidadeRoute,
  HistoriaRoute: HistoriaRoute,
  LoginRoute: LoginRoute,
  OrgulhoMaranhenseRoute: OrgulhoMaranhenseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
